### ISSUE TITLE
Can't build Android anymore after adding this plugin

### ISSUE THREAD

**Issue by Ahmadre** [Glartek/flutter-unity#10]
**Describe the bug**
I tried to build with and without this plugin my android project, but whenever I add this plugin, my Flutter Android App is not recognizing any Plugin anymore.

**To Reproduce**
1. Follow the steps for android in the readme.
2. Add flutter_unity to your pubspec.yaml.
3. Add **path_provider** to this project!!
4. Try to debug or release run

**Expected behavior**
My Plugins are recognized when using this plugin.

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 10 (API 29)
 - Unity: 2019.3.*
 - Flutter 1.21.0

**Error**
```batch
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
W/FlutterActivity( 9776): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@30d59d2) but could not find and invoke the GeneratedPluginRegistrant.
Connecting to VM Service at ws://127.0.0.1:51373/VZI-WrkSf1Y=/ws
E/flutter ( 9776): [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter ( 9776): #0      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:158
E/flutter ( 9776): <asynchronous suspension>
E/flutter ( 9776): #1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:333
E/flutter ( 9776): #2      MethodChannelPathProvider.getApplicationDocumentsPath 
package:path_provider_platform_interface/src/method_channel_path_provider.dart:50
E/flutter ( 9776): #3      getApplicationDocumentsDirectory 
package:path_provider/path_provider.dart:109
E/flutter ( 9776): #4      AppService.init 
package:app/app/service.dart:24
E/flutter ( 9776): #5      main 
package:app/main.dart:20
E/flutter ( 9776): #6      _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:233:25)
E/flutter ( 9776): #7      _rootRun  (dart:async/zone.dart:1190:13)
E/flutter ( 9776): #8      _CustomZone.run  (dart:async/zone.dart:1093:19)
E/flutter ( 9776): #9      _runZoned  (dart:async/zone.dart:1630:10)
E/flutter ( 9776): #10     runZonedGuarded  (dart:async/zone.dart:1618:12)
E/flutter ( 9776): #11     _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:225:5)
E/flutter ( 9776): #12     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter ( 9776): #13     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 9776):
Exited
```

**Comment by cookiejarlid** [comment]
I'm unable to reproduce any issues, mentioned or unmentioned here, using the latest stable flutter version (currently 1.20.2), the latest flutter_unity (currently 0.2.1+4) and the included unity example project (using Unity 2019.4 LTS), and properly following the steps described in the documentation.

This plugin has also been successfully tested with several AR Unity projects, by me and others, and any issues you may have that aren't reproducible with the included example projects, you will unfortunately have to resolve them yourself.
That being said, I'll gladly clarify any step described in the documentation that you may be having difficulty with, so feel free to re-open this issue if that's the case.

**Comment by Ahmadre** [comment]
Actually a lot of people aren't and can't use stable, because a lot of flutter-apis are missing and fixes.

We're a company and using Flutter master and beta channel. Mostly beta and also the actual android build looks different then the one here in the example folder.

It's a pity that glartek is just closing this issue without getting more clear to the exact issue (`Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@30d59d2) but could not find and invoke the GeneratedPluginRegistrant`).

And yes I tried your example folder. But when using Flutter beta (which is the actual stable for future projects), it's not possible. Sorry but we can't integrate this plugin and we would be happy if you would just integrate this into an App which uses:

- FirebaseCloudMessaging
- Path Provider

Just in case we feel "understanded".

thanks.

**Comment by marcotuna** [comment]
Hi @Ahmadre, currently supporting not stable API's are not in our top priorities list. We strive to get community feedback and contributions in order to improve and maintain this project, you can try to provide the most accurate description possible so others can help you in order to run this plugin with the Flutter beta API's, we will leave this one for the community. For now we don't have this requirement, that doesn't mean that we won't put effort into this in the future.

**Comment by Ahmadre** [comment]
@cookiejarlid @marcotuna all right. I switched now to stable 1.20. I'll give it a try :) But thank you all for the quick response! 

I have to say you all are doing a great job really!

**Comment by Ahmadre** [comment]
IT'S WORKING!!!! THANK YOU SOOO MUCH @cookiejarlid !!!!

**Comment by Ahmadre** [comment]
ok i know what the actual problem is: The documentation in the readme is not correct and lacks in detailness:

"1. Copy the unityExport folder to `<your_flutter_project>/android/unityExport`." ---> Here's the problem.

It should be clarified, that Unity is exporting as `unityLibrary` with `launcher`, and seperate **build.gradle** and **settings.gradle**! That leads to the problems i just saw earlier here in some issues. 

Step 1. should be decscribed like:

"1. Create a folder named `unityExport` if it does not exist in `<your_flutter_project>/android/` and select that folder for your export."

My problem was not stable, it's working on master! The cause of my issue was that when I exported and executed the transmografiy command all my project was a mess after that.

@cookiejarlid maybe you can update the first android step for setup flutter
