### ISSUE TITLE
Does this work with AR Foundation?

### ISSUE THREAD

**Issue by giovannowarli** [Glartek/flutter-unity#11]
Well-done with this package and really appreciate it! The example worked flawlessly. Just wondering if this works with AR? I tried including AR Foundation (ARkit) to the project, and tried to run it to a physical device (iphone). And got the following error.

2020-08-22 06:06:36.264217+0700 Runner[495:36813] Metal API Validation Enabled
2020-08-22 06:06:36.405163+0700 Runner[495:37060] flutter: Observatory listening on http://127.0.0.1:53927/_IwMpeW9Chc=/
2020-08-22 06:06:38.018470+0700 Runner[495:36813] Built from '2019.3/staging' branch, Version '2019.3.5f1 (d691e07d38ef)', Build type 'Release', Scripting Backend 'il2cpp'
-> applicationDidFinishLaunching()

Setting UIViewControllerBasedStatusBarAppearance to NO is no longer supported.
Apple actively discourages that, and all application-wide methods of changing status bar appearance are deprecated

-> applicationWillEnterForeground()
-> applicationDidBecomeActive()
-> applicationWillEnterForeground()
-> applicationDidBecomeActive()
[Subsystems] Discovering subsystems at path /var/containers/Bundle/Application/A5A6CB63-972B-450C-A3B0-D57CAB240E5B/Runner.app/Frameworks/UnityFramework.framework/Data/UnitySubsystems
[Subsystems] No descriptors matched for  examples in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json.
[Subsystems] 1 'inputs' descriptors matched in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json
[Subsystems] No descriptors matched for  displays in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json.
[Subsystems] 1 'meshings' descriptors matched in UnitySubsystems/UnityARKit/UnitySubsystemsManifest.json
GfxDevice: creating device client; threaded=1
2020-08-22 06:06:38.094059+0700 Runner[495:37049] flutter: onUnityViewCreated
Initializing Metal device caps: Apple A11 GPU
(lldb)

**Comment by cookiejarlid** [comment]
Hi @giovannowarli, the short answer is Yes. In fact, the iOS support was initially tested against the AR Foundation samples. At the time I used the [recommended version](https://github.com/Unity-Technologies/arfoundation-samples#what-version-should-i-use) for the Unity version I was using (2019.3).

Seeing as you've already managed to run the example project, it's unlikely that you're simply misconfiguring something on the plugin side.

What exactly happens when you run it? Does it crash?
Have you tried running the AR Foundation samples directly?

**Comment by ericloureiro** [comment]
Hello @giovannowarli, any news on your project?

We have a project where we use ARFoundation (ARKit) on a real device (iPhone SE 2020) and it works real nice.
Our team managed to run AR Foundation samples mentioned by @cookiejarlid on the device as well.

Can you give us an update or we can close this issue?
