### ISSUE TITLE
Problem setting up for iOS

### ISSUE THREAD

**Issue by moster67** [Glartek/flutter-unity#16]
I tried the sample project and it runs fine in Android. Many thanks for your work. Much appreciated.

However, I have difficulties to get it up and running on iOS. I followed the instructions for setting it up with xcode but I simply cannot get it to work. I am still on Mojave and xcode Version 11.3.1 (I cannot upgrade for various reasons). 
Also, my experience with xcode and ios development is nearly null and this is the reason I went with Flutter in the first place.

Any chance someone could write down more detailed instructions for iOS (step-by-step) to get the example running? A video on YouTube might be even better.
I think this would benefit also others when using your plugin.

Thanks.

**Comment by jamesncl** [comment]
Hi, I'm also facing problems building for iOS, maybe we can help each other. What step do you get to and what specifically do you mean by "cannot get it to work"?

I'm also on Mojave (I'm using an old cheese-grater mac pro, can't afford to buy a newer one!), XCode 11.3.1, Unity 2020.1.6. What version of Unity are you using?

When attempting to build in Unity for iOS I get these build errors:

> Assets/Scripts/FlutterUnityPlugin.cs(48,10): error CS0246: The type or namespace name 'DllImportAttribute' could not be found (are you missing a using directive or an assembly reference?)
> 
> Assets/Scripts/FlutterUnityPlugin.cs(48,10): error CS0246: The type or namespace name 'DllImport' could not be found (are you missing a using directive or an assembly reference?)
> 

It seems that Unity 2020.1.6 doesn't like this part of the [example unity flutter plugin code](https://github.com/Glartek/flutter-unity/blob/master/example/unity/FlutterUnityExample/Assets/FlutterUnityPlugin.cs):

```
    #if UNITY_IOS
        [DllImport("__Internal")]
        private static extern void FlutterUnityPluginOnMessage(string data);
    #endif
```

I'm going to try and figure out how to fix it now...

**Comment by jamesncl** [comment]
Now I'm stuck on this error during build - is this where you're getting stuck also?

```
/Volumes/Data/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_unity-0.2.1+5/ios/Classes/FlutterUnityPlugin.m:3:9: fatal error: 'UnityFramework/UnityFramework.h'
    file not found
    #import <UnityFramework/UnityFramework.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description

```

**Comment by jamesncl** [comment]
When you get to this step in the iOS setup:

> Go to File > Add Files to "Runner"..., and add <your_flutter_project>/ios/UnityProject/Unity-iPhone.xcodeproj.

Make sure you add to the ROOT of the workspace. To make sure you do this, it might be best to right-click empty space in the inspector, then choose 'Add files to Runner...'

**Comment by ericloureiro** [comment]
Hello @moster67, any news from your project? 

I would like to hear more from your problem.
Our team was able to setup and run our solution to work on iOS. 

I will be glad to help!

**Comment by ferryl** [comment]
Hello, @ericloureiro we also have the problem with the "UnityFramework/UnityFramework.h' file not found " 
our specs:
Flutter 1.22.4 stable
Xcode 12.4
Unity 2019.4
We followed all the steps of the readme step by step, but it was impossible to compile it. 
What more info do you need to help?

**Comment by MarselGarcia** [comment]
Hello @ferryl , make sure you have the Classes/unity folder too, the same happen to me once.
![Screen Shot 2021-03-11 at 1 00 11 PM](https://user-images.githubusercontent.com/50886337/110833100-10818500-826a-11eb-8bb2-a4f6905dadee.png)

**Comment by ferryl** [comment]
Thank you @MarselGarcia, but I paid attention to this folder and unfortunately it is not the source of the problem :/

**Comment by cookiejarlid** [comment]
I'm assuming this is solved? Feel free to reopen if needed.
