### ISSUE TITLE
Flutter unity_export_transmog command fail

### ISSUE THREAD

**Issue by figux01** [Glartek/flutter-unity#2]
**Describe the bug**
After install the plugin, i try to run this command as said in the documentation:
`flutter pub run flutter_unity:unity_export_transmog`

Got this output:
`Could not find bin/unity_export_transmog.dart in package flutter_unity.`

**To Reproduce**
1. intall the plugin
2. Run this command : `flutter pub run flutter_unity:unity_export_transmog`
3. See error

**Comment by cookiejarlid** [comment]
The correct command is `flutter pub run flutter_unity:unity_export_transmogrify`, as stated in the documentation.

**Comment by figux01** [comment]
> The correct command is `flutter pub run flutter_unity:unity_export_transmogrify`, as stated in the documentation.

Great this work but i get this in the console output:
`Directory not found: `../flutter/agc/android/unityExport/launcher/src/main/res`

is this an error ?

**Comment by figux01** [comment]
Now when i try to build the app, here is what i get
![image](https://user-images.githubusercontent.com/36422646/86487085-add80100-bd4c-11ea-9b91-032200a079f6.png)

**Comment by cookiejarlid** [comment]
I would recommend that you **carefully** follow all the steps described in the documentation in order to avoid misconfiguration related problems.

**Comment by cookiejarlid** [comment]
I'm closing this issue since the initially reported problem wasn't a bug and has been clarified. Feel free to open a new issue if needed.

**Comment by Ahmadre** [comment]
same here, the flutter command above deleted my build.gradle from unityExport...

**Comment by subaharan** [comment]
I am facing the same issue. Please give a solution for this. Thanks in advance

**Comment by subaharan** [comment]
> > The correct command is `flutter pub run flutter_unity:unity_export_transmogrify`, as stated in the documentation.
> 
> Great this work but i get this in the console output:
> `Directory not found: `../flutter/agc/android/unityExport/launcher/src/main/res`
> 
> is this an error ?

Did you find a solution for this? I am also facing the same issue.
