### ISSUE TITLE
Linker issue on iOS

### ISSUE THREAD

**Issue by artificerchris** [Glartek/flutter-unity#22]
After following the configuration steps and trying to build for iOS, I get the following linker message.
```
Undefined symbols for architecture arm64:
      "_FlutterUnityPluginOnMessage", referenced from:
          _Messages_FlutterUnityPluginOnMessage_mA8EF48D78A17E613D890457ACF4A0DF
          21A4E0853 in Assembly-CSharp.o
         (maybe you meant:
         _Messages_FlutterUnityPluginOnMessage_mA8EF48D78A17E613D890457ACF4A0DF2
         1A4E0853)
    ld: symbol(s) not found for architecture arm64
```

1. Setup a new project or use the example from the repo
2. Configure project for iOS
3. Build using either xcode or flutter run
4. Observe error in build output.

**Expected behavior**
I would expect the project to build and deploy to my device.

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 14

**Comment by artificerchris** [comment]
Linker settings were wrong.

**Comment by Jiffer** [comment]
I am getting this error too. @artificerchris I'm curious what you needed to change in your linker settings. 

I followed the setup described with the example project. including adding other linker flags 
> -Wl, -U, _FlutterUnityPluginOnMessage 

to the Unity-Iphone project

what did you do to resolve this? 
thanks

**Comment by artificerchris** [comment]
So, my issue ended up being how I added the linker flags. When you add them, they all go together, not on individual lines or anything. Double click on ‘other linker flags’ then click plus and paste that list of flags exactly. That was my problem was breaking them onto their own lines or trying to quote them. Make sure you’re actually setting them in the project settings and not on the Unity-IPhone target instead.

**Comment by Jiffer** [comment]
Thanks for the quick reply. I believe thats what I've done here. 

Although, the steps say to add this flag to Unity-iPhone. I've tried adding these flags to both Unity-iPhone and Runner together and each individually without luck.


Is this what you're suggesting?

![Screen Shot 2021-02-25 at 2 19 06 PM](https://user-images.githubusercontent.com/2372348/109219741-3b9dac00-7775-11eb-82ce-68f7ea1edc89.png)

**Comment by artificerchris** [comment]
Yeah, the issue with putting them on the target is you aren’t actually building the unity-iPhone target, that’s what gets built in a standalone unity project. So they need to go on the project so it knows when linking in the unity project to your build target to add those flags.
