### ISSUE TITLE
Is it possible to run dynamic scene

### ISSUE THREAD

**Issue by eniserkaya** [Glartek/flutter-unity#24]
I run different scenes on my web application using react.js via webGL, but you know that webgl can not support the mobile browser.

I want to develop a mobile application to run the unity scenes dynamically.

Thanks to this library, i developed an application which runs a unity project, but i can not change the screen dynamically. Each scene is actually one unity project. Is it possible to dynamically run a unity project or scene or etc. via this library? So i have a lot of unity projects. Is it possible to run it dynamically in runtime, to download it from any url and to run inside a flutter application.

Thanks

**Comment by Ahmadre** [comment]
This is not related to this plugin. You've to ask in Unity Blog-Forums.

But I would suggest you to use Prefabs rather then different scenes. Use: .SetActive(3DModelObject) for de/activating prefabs

**Comment by gOzaru** [comment]
If so, can this plugin use a multiple scenes?
I meant, one scene A in menu page and another scene B in view page???
