### ISSUE TITLE
[feature]: macOS Desktop support

### ISSUE THREAD

**Issue by Ahmadre** [Glartek/flutter-unity#27]
I am trying to build a unity-player for macOS Apps. Is it even possible?

**Comment by cookiejarlid** [comment]
Hi @Ahmadre,

That is out of scope for this plugin.

**Comment by Ahmadre** [comment]
> Hi @Ahmadre,
> 
> 
> 
> That is out of scope for this plugin.

It's ok that this is out of scope. But why did you close it? Maybe I can help contribute to this, if you want to work with the community. Sorry but this is a community right?
