### ISSUE TITLE
UnityFramework does not contain bitcode.

### ISSUE THREAD

**Issue by MarselGarcia** [Glartek/flutter-unity#31]
I tried setting up the example project and follow all steps, but Xcode throws an error when building:

'/Users/Marsel/Library/Developer/Xcode/DerivedData/Runner-auggbmmkjsruwmaqfgadcbpzugzp/Build/Products/Debug-iphoneos/UnityFramework.framework/UnityFramework' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/Marsel/Library/Developer/Xcode/DerivedData/Runner-auggbmmkjsruwmaqfgadcbpzugzp/Build/Products/Debug-iphoneos/UnityFramework.framework/UnityFramework' for architecture arm64

![Screen Shot 2021-03-11 at 2 52 30 PM](https://user-images.githubusercontent.com/50886337/110846138-71fd2000-8279-11eb-839e-ef7955ba6b43.png)

![Screen Shot 2021-03-11 at 2 52 17 PM](https://user-images.githubusercontent.com/50886337/110846131-6f9ac600-8279-11eb-98bd-abb6f07b9e34.png)

I've already set in Build Setting Enable Bitcode to NO and added the requiere linker flags.

I tried `flutter clean`, `pod deintegrate`, deleting Derived Data folder but still getting the same error.

Both Unity 2019.4.2f1 and 2020.2.6f1.
Xcode 12.4

**Comment by jaboyc** [comment]
I'm having this issue as well. Tried a variety of things like `flutter clean`, deleting DerivedData folder, and setting `Enable Bitcode` to false for all projects/targets to no avail.

**Comment by MarselGarcia** [comment]
Finally found a solution.

Just need to add `config.build_settings['ENABLE_BITCODE'] = 'NO'` on your post_install on podfile.

![Screen Shot 2021-03-11 at 8 28 17 PM](https://user-images.githubusercontent.com/50886337/110877965-552c1100-82a8-11eb-9e63-b77fe36a27b8.png)

With this addition now your Pods targets should have Enable Bitcode set to 'No'

![Screen Shot 2021-03-11 at 8 30 57 PM](https://user-images.githubusercontent.com/50886337/110878178-b653e480-82a8-11eb-8bda-bd2f36062548.png)
