### ISSUE TITLE
Unity player changes the screen orientation of Flutter App permanently

### ISSUE THREAD

**Issue by Parassharmaa** [Glartek/flutter-unity#4]
**Describe the bug**
When navigating from Screen A (Portrait) to Screen B (Unity Player with Landscape Orientation), the screen orientation is permanently set to landscape. Navigating back to Screen A from Screen B also keeps the app in Landscape mode (which was enforced by Screen.orientation API in Unity)

**Expected behavior**
Navigating back to Screen A from Screen B should bring the App orientation to default.

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 10

**Comment by cookiejarlid** [comment]
This happens because Unity not only ignores the OS-level screen orientation settings, it also explicitly sets the Activity's requested orientation to Portrait/Landscape. I have already come up with a workaround for this which will be included in the next release.

**Comment by cookiejarlid** [comment]
flutter_unity 0.2.1+2 has been released and fixes this issue.

**Comment by Parassharmaa** [comment]
https://github.com/Glartek/flutter-unity/commit/4a216a7720c9a69411aac5b6c15574dab0f128e6
