### ISSUE TITLE
Android Touch is not working

### ISSUE THREAD

**Issue by Ahmadre** [Glartek/flutter-unity#43]
**Describe the bug**
I am trying since __weeks__ to fix the android version to be able to react to TouchEvents, but I don't know why Touch is not working for Android. We implemented the New Input System and it's working very good for iOS. No problems there. But on Android nothing is happening and no error messages, just this:

![Bildschirmfoto 2021-12-15 um 20 57 09](https://user-images.githubusercontent.com/18512224/146256214-f0032a16-257c-48de-81eb-cba864637386.png)

**To Reproduce**
1. Import the new Input System into your Project
2. Import one of the samples from Unity itself
3. Try to run your app on Android
4. Try out the Touch

**Expected behavior**
Android Touch is working.

**Smartphone (please complete the following information):**
 - Device: Pixel 4 - Android
 - OS: 11

**Unity**
- Version: 2020.3.19f1
- Input-System Version: 1.2.0

**Additional context**
I did a lot of Research, asked in Groups, Discord, Googled, looked up the Warnings....nothing!

**Comment by Ahmadre** [comment]
@marcotuna any idea here?

**Comment by Ahmadre** [comment]
Update: tried with Unity 2019.4.14f1 also and lower versions of my plugins but touch also not working :(

**Comment by Ahmadre** [comment]
Update: it's not working only on some Android devices. But it's working on others. Maybe a JNI Issue

**Comment by MarselGarcia** [comment]
Same happened to me, new input system didn't work on Samsung devices. I had to roll back to old input system.

**Comment by Ahmadre** [comment]
> Same happened to me, new input system didn't work on Samsung devices. I had to roll back to old input system.

Thanks. I downgraded to Old Input System and it's working now :)
