### ISSUE TITLE
 FlutterUnityPlugin.Messages.Send failing in Release Build

### ISSUE THREAD

**Issue by Parassharmaa** [Glartek/flutter-unity#5]
The `FlutterUnityPlugin.Messages.Send` fails with ClassNotFoundException in `Release` Build.

It works fine in debug build.

**Log**
```
07-06 16:20:14.349 20359 20419 E Unity   : AndroidJavaException: java.lang.ClassNotFoundException: com.glartek.flutter_unity.FlutterUnityPlugin
07-06 16:20:14.349 20359 20419 E Unity   : java.lang.ClassNotFoundException: com.glartek.flutter_unity.FlutterUnityPlugin
07-06 16:20:14.349 20359 20419 E Unity   :      at java.lang.Class.classForName(Native Method)
07-06 16:20:14.349 20359 20419 E Unity   :      at java.lang.Class.forName(Class.java:454)
07-06 16:20:14.349 20359 20419 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
07-06 16:20:14.349 20359 20419 E Unity   :      at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
07-06 16:20:14.349 20359 20419 E Unity   :      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:83)  
07-06 16:20:14.349 20359 20419 E Unity   :      at android.os.Handler.dispatchMessage(Handler.java:103)                 
07-06 16:20:14.349 20359 20419 E Unity   :      at android.os.Looper.loop(Looper.java:214)
07-06 16:20:14.349 20359 20419 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
07-06 16:20:14.349 20359 20419 E Unity   : Caused by: java.lang.ClassNotFoundException: com.glartek.flutter_unity.FlutterUnityPlugin
```

**Comment by cookiejarlid** [comment]
It looks like something is off with your configuration. Could you attempt to run the included example app in Release Mode by going to `Run` > `Flutter Run 'main.dart' in Release Mode` in **Android Studio**? You should get the following messages:

```
I/flutter: onUnityViewMessage
I/flutter: SetRotationSpeed: 30
```

**Comment by Parassharmaa** [comment]
I tried `Run` > `Flutter Run 'main.dart' in Release Mode`, it works fine.

But the above exception occurs on using `flutter build apk`. It might be due to the obfuscation of the Class name.

Any ideas how can it be fixed?

**Comment by cookiejarlid** [comment]
Ok, I was able to reproduce it. Building the APK with `flutter build apk --no-shrink` instead of `flutter build apk` solves the problem, but it doesn't sound like an ideal solution to me. There's probably a better way to do it, but that's all I've got for now.

**Comment by Parassharmaa** [comment]
A solution may involve using Pro-guard rules: https://developer.android.com/studio/build/shrink-code#keep-code

**Comment by cookiejarlid** [comment]
There's a better alternative, which is also mentioned in your link: Adding a `@Keep` annotation to the `FlutterUnityPlugin` class. I'll be applying this fix soon. Thanks :+1:
