### ISSUE TITLE
clang: error: no such file or directory: '_FlutterUnityPluginOnMessage'

### ISSUE THREAD

**Issue by klepov** [Glartek/flutter-unity#6]
**Describe the bug**
I can't build for iOS. I follow the instructions, but I always get the same error - clang: error: no such file or directory: '_FlutterUnityPluginOnMessage'
Command Ld failed with a nonzero exit code <---- **logs from xCode**

**another log from Idea**

Failed to build iOS app
Error output from Xcode build:
↳
     ** BUILD FAILED **

Xcode's output:
↳
     /Users/*/IdeaProjects/flutter-unity-*/ios/Classes/FlutterUnityPlugin.m:3:9: fatal error: 'UnityFramework / UnityFramework.h' file not found
     #import <UnityFramework / UnityFramework.h>
             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     1 error generated.
     note: Using new build system
     note: Building targets in parallel
     note: Planning build
     note: Constructing build description

**To Reproduce**
1. follow the instructions for ios build

**Smartphone (please complete the following information):**
 - iPhone 11
 - Flutter 1.17.5
 - xCode 11.6 (11E708)
 - Unity 2019.3.7f1

P.S. sorry for my english

**Comment by cookiejarlid** [comment]
Are you using the the [included Unity project](https://github.com/Glartek/flutter-unity/tree/master/example/unity/FlutterUnityExample)?
Could you show me how you're doing step 4. of [Configuring your Flutter project : iOS](https://github.com/Glartek/flutter-unity#ios-2), specifically how you're adding to `Other Linker Flags `?

**Comment by klepov** [comment]
everything worked out. made according to the tutorial
