### ISSUE TITLE
Black Screen of window of unity  in flutter

### ISSUE THREAD

**Issue by Ehsan-Akhlaghy** [Glartek/flutter-unity#8]
Hello everyone,
after embed unity in flutter, window of unity in flutter is black, the point is it shows splash screen of unity but after that I got Black Screen. I think its some issue about exporting in unity. whenever I build APK inside unity, it works but when I embed it in flutter, I mean do steps of exporting project for use in flutter, I got Black Screen. I use Unity 2019.3.13f1.  what is problem? in which version of unity, flutter tested?

Thanks

**Comment by Ahmadre** [comment]
You got the same problem as me my friend: https://github.com/Glartek/flutter-unity/issues/10

This is because after this plugin is added your android won't get run afterwards....

**Comment by cookiejarlid** [comment]
I'm unable to reproduce any issues, mentioned or unmentioned here, using the latest stable flutter version (currently 1.20.2), the latest flutter_unity (currently 0.2.1+4) and the included unity example project (using Unity 2019.4 LTS), and properly following the steps described in the documentation.

This plugin has also been successfully tested with several AR Unity projects, by me and others, and any issues you may have that aren't reproducible with the included example projects, you will unfortunately have to resolve them yourself.
That being said, I'll gladly clarify any step described in the documentation that you may be having difficulty with, so feel free to re-open this issue if that's the case.

**Comment by rahulmool** [comment]
> I'm unable to reproduce any issues, mentioned or unmentioned here, using the latest stable flutter version (currently 1.20.2), the latest flutter_unity (currently 0.2.1+4) and the included unity example project (using Unity 2019.4 LTS), and properly following the steps described in the documentation.
> 
> This plugin has also been successfully tested with several AR Unity projects, by me and others, and any issues you may have that aren't reproducible with the included example projects, you will unfortunately have to resolve them yourself.
> That being said, I'll gladly clarify any step described in the documentation that you may be having difficulty with, so feel free to re-open this issue if that's the case.

You said you have tested several AR Unity projects with this project. Is the process of doing so any different from the documentation provided?
